filter:
    excluded_paths: [vendor/*, tests/*, src/config/*, src/views/*]

tools:
    external_code_coverage: true
    php_mess_detector: true
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor, tests, src/config, src/views]